version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      target: dev
    container_name: myy_jobs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - redis

    environment:
      - PORT=3000
      - REDIS_HOST=redis
