version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      target: dev
    container_name: my_jobs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - redis

    environment:
      - PORT=3000
      - REDIS_HOST=redis


  worker:
    build:
      context: .
      target: dev
    container_name: my-worker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm run worker